node {

	currentBuild.setResult('SUCCESS')

	try {

		def commitId
		def imageName = "agill17/node_app"
		def image
		def container
		def appDir = "Jenkinsfile/201"

		def masterIp

		stage('Prepare') {
			def git = checkout scm
			commitId = git.GIT_COMMIT
		}

		dir(appDir){

			nodejs('nodejs') {
				
				stage('Install dependencies') {
					sh "npm install --only=dev"
				}

				stage('Run npm Tests') {
					sh "npm test"
				}
			}

			stage('Build Image') {
				image = docker.build("${imageName}:${env.BUILD_NUMBER}-${commitId}")
			}

			stage ('Run Container') {
				container = docker.image("${imageName}:${env.BUILD_NUMBER}-${commitId}").run("-dp 3000:3000")
				env.CONTAINER_ID = container.id
			}

			stage ('Verify local deployment') {
				masterIp = sh (returnStdout: true, script: 'hostname -I').split(" ")[1]
				def content = sh(returnStdout: true, script: "curl ${masterIp}:3000")
				print ln content
			}

			stage ('Push Docker image') {
				docker.withRegistry('https://registry.hub.docker.com','docker_hub') {
					image.push()
				}
			}

		}

	} catch(err) {


	} finally {
		container.stop()
		sh "docker rmi ${image.id}"
	}
	

}