node {

	currentBuild.setResult('SUCCESS')

	try {

		def commitId
		def imageName = "agill17/node_app"
		def image
		def container
		def appDir = "Jenkinsfile/201"

		stage('Prepare') {
			def git = checkout scm
			commitId = git.GIT_COMMIT
		}

		dir(appDir){

			nodejs('nodejs') {
				
				stage('Install dependencies') {
					sh "npm install --only=dev"
				}

				stage('Run npm Tests') {
					sh "npm test"
				}
			}

			stage('Build Image') {

			image = docker.build("${imageName}:${env.BUILD_NUMBER}-${commitId}")

			}

			stage ('Push Docker image') {
				docker.withRegistry('https://registry.hub.docker.com','docker_hub') {
					image.push()
				}
				sh "docker rmi ${image.id}"
			}


			stage ('Run Container') {
				container = docker.image("${imageName}:${env.BUILD_NUMBER}-${commitId}").run("-dp 3000:3000")
				env.CONTAINER_ID = container.id
			}

			input "Check deployment at ip:3000"

			stage('Clean up container'){
				container.stop()
			}
		}



	} catch(err) {


	}
	

}