node {

	currentBuild.setResult('SUCCESS')
	def container
	def commitId
	def imageName = "agill17/node_app"
	def image
	def appDir = "Jenkinsfile/201"

	def masterIp
	
	try {

		

		stage('Prepare') {
			def git = checkout scm
			commitId = git.GIT_COMMIT
		}

		dir(appDir){

			nodejs('nodejs') {
				
				stage('Install dependencies') {
					sh "npm install --only=dev"
				}

				stage('Run npm Tests') {
					sh "npm test"
				}
			}

			stage('Build Image') {
				image = docker.build("${imageName}:${env.BUILD_NUMBER}-${commitId}")
			}

			stage ('Run Container') {
				container = docker.image("${imageName}:${env.BUILD_NUMBER}-${commitId}").run("-dp 3000:3000")
			}

			stage ('Verify local deployment') {
				masterIp = sh (returnStdout: true, script: 'hostname -I').split(" ")[1]
				//manually verify deployment then later section automate this

				input "Check deployment on ${masterIp}:3000"
			}

			stage ('Push Docker image') {
				docker.withRegistry('https://registry.hub.docker.com','docker_hub') {
					image.push()
				}
				sh "docker rmi ${image.id}"
				println container.methods
				exit 1
			}

		}

	} catch(err) {
		container.stop()
		currentBuild.setResult('FAILURE')
		emailext(attachLog: true, body: 'FAILED!', compressLog: true, mimeType: 'text/html', recipientProviders: [developers()], subject: '${JOB_NAME}:${BUILD_NUMBER}')
		throw err

	} finally {
		runningContainer = sh(returStdout: true, script: "docker ps -a | grep ${image.id} | wc -l")
		if (runningContainer == "1") {
			container.stop()
		}

	}

}