#!groovy 

node {

	def mvn_home
	def app_dir = "Jenkinsfile/101/"

	stage('Prepare') {
		checkout scm
		mvn_home = tool name: 'maven_home'
	}

	stage('Cleanup') {
		dir(app_dir) {
			target = new File('target')
			if ( target.exists() ){
				target.deleteDir()
			}
			println target.exists()
			assert !target.exists()
		}
	}

	stage('Build') {
		dir (app_dir) {
			sh "mvn_homen package"
		}
	}

	stage('Verify package exists') {
		def app_to_check = "${workspace}/${app_dir}/target/grants.war"
		def app_package = new File(app_to_check)
		println app_package.exists()
		sh "ls -al $app_to_check"
		assert app_package.exists()
	}

	stage('Results'){
		dir(app_dir) {
			junit '**/target/surefire-reports/*.xml'
		}
	}


}