@Library('library') _

node {
  
  def imgTag = "agill17/tomcat:${env.BUILD_NUMBER}"
  def contPort = "8080" 
  def hostPort = "8088"  
  def credId = 'docker_hub'
  def file_path_to_dockerfile = "Docker/artifactory" 

  stage ('build and push') {
    buildImage(file_path_to_dockerfile , credId, imgTag)
  }
   
  stage ('run container') {
    deployContainer(imgTag, "-p ${hostPort}:${contPort}")
  }

}
