node {
	
	stage ('clone') {
		def gitVar = checkout scm
		println gitVar
		println gitVar.GIT_COMMIT
	}

	stage ('test running container') {
		def mvnImg = docker.image("maven:latest")
		mvnImg.pull()
		mvnImg.inside {
			dir('Jenkinsfile/103') {
				sh 'ls -al'
				sh 'pwd'
				sh 'mvn package'
			}
		}
	}
}