node {
	
	def app_dir = "$workspace/Jenkinsfile/102"
	def docker_cred_id = 'docker_hub'
	def docker_img_name = "agill17/npm"
	def commitId

	stage ('rm all containers up') {
		sh "docker container rm -f node_app"
	}


	stage ('clone') {
		checkout scm
		commitId = sh returnStdout: true, script: 'git rev-parse --short HEAD'
		
		// only works in multi-branch job
		//branch_name = "${env.BRANCH_NAME}"
	}


	stage ('install dev dependencies') {
		
		nodejs('nodejs') {
			dir(app_dir) {
				sh 'npm install --only=dev'
				sh 'npm test'
			}
		}

	}

	def imageNameTag = "${docker_img_name}:${env.JOB_NAME}-${env.BUILD_NUMBER}"

	stage ('docker build && push') {
		
		dir (app_dir) {
			docker.withRegistry('https://registry.hub.docker.com', docker_cred_id) {
			    def img = docker.build(imageNameTag, "  -f Dockerfile .").push("${commitId}")
			}
		}
	}

	stage ('deploy container locally') {
		sh "docker container run -dp 3000:3000 \
			--name='node_app' \
			$imageNameTag "
	}

	stage ('clean up') {
		sh "docker container rm -f node_app"
		sh "docker image rm -f $imageNameTag"

	}

}