node {
	
	def app_dir = "$workspace/Jenkinsfile/102"
	def mvn = tool name: 'maven_home'
	def nodejs = tool name: 'nodejs'
	def run_mvn = "${mvn}/bin/mvn"
	def workspace = "${workspace}"
	def branch_name
	def commit_id

	stage ('clone') {
		checkout scm
		commit_id = sh(script: 'git rev-parse --short HEAD', returnStdout: true)
		branch_name = env.BRANCH_NAME
		//branch_name = sh(script: env.BRANCH_NAME, returnStdout: true)
	}


	stage ('install dev dependencies') {

	}



}