node {
	
	def app_dir = "$workspace/Jenkinsfile/102"
	def mvn = tool name: 'maven_home'
	def run_mvn = "${mvn}/bin/mvn"
	def workspace = "${workspace}"
	def docker_cred_id = 'docker_hub'
	def docker_img_name = "agill17/npm"
	def branch_name
	def commit_id

	stage ('clone') {
		checkout scm
		commit_id = sh(script: 'git rev-parse --short HEAD', returnStdout: true)
		branch_name = env.BRANCH_NAME
		println commit_id
		println branch_name
	}


	stage ('install dev dependencies') {
		
		nodejs(nodeJSInstallationName: 'nodejs') {
			dir(app_dir) {
				sh 'npm install --only=dev'
				sh 'npm test'
			}
		}

	}
	def docker_img_tag = "${env.JOB_NAME}-${env.BUILD_NUMBER}-${commit_id}"

	if (branch_name == "master") {

		docker_img_tag += "-latest"

	}
	println "${docker_img_name}:{docker_img_tag}"


	stage ('docker build && push') {
		
		dir (app_dir) {
			docker.withRegistry('https://index.docker.io/v1/', docker_cred_id) {
				def img = docker.build("${docker_img_name}:${docker_img_tag}", "-f .")
				img.push()
			}
		}

	}



}